### ISSUE TITLE
issue with files name

### ISSUE THREAD

**Issue by reuspppp** [p-ranav/saveddit#6]
just a small problem, the " character is illegal in windows file name so the script crash when it encounters one.

**Comment by p-ranav** [comment]
Did you mean directory names?

I've changed the directory name construction so that anything that isn't alphanumeric or '_' is stripped out.

**Comment by wanghaisheng** [comment]
@p-ranav  what about this one 

```
saveddit search  AceAttorney  -q "Ace Attorney " -o .
Traceback (most recent call last):
  File "c:\users\dubo\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dubo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dubo\anaconda3\Scripts\saveddit.exe\__main__.py", line 7, in <module>
  File "c:\users\dubo\anaconda3\lib\site-packages\saveddit\saveddit.py", line 356, in main
    downloader.download(args)
  File "c:\users\dubo\anaconda3\lib\site-packages\saveddit\search_subreddits.py", line 100, in download
    os.makedirs(search_dir)
  File "c:\users\dubo\anaconda3\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\dubo\anaconda3\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] filenotfound。: '.\\www.reddit.com\\q\\Ace Attorney \\AceAttorney'
```
