### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by mubashir-rehman** [p-ranav/saveddit#9]
I am using Linux Mint 20.1. The following error occured.

Traceback (most recent call last):
  File "/home/mobi/.local/bin/saveddit", line 8, in <module>
    sys.exit(main())
  File "/home/mobi/.local/lib/python3.8/site-packages/saveddit/saveddit.py", line 68, in main
    downloader.download(args.o,
  File "/home/mobi/.local/lib/python3.8/site-packages/saveddit/subreddit_downloader.py", line 79, in download
    os.makedirs(category_dir)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Downloads'

**Comment by mubashir-rehman** [comment]
This might be helpful https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied/36469464

**Comment by mubashir-rehman** [comment]
Edited path from '/Downloads' to '~/Downloads'. It is working now
